export const ENVS = {
  PORT: process.env.PORT || 3000,
  FIRE_BASE_API_KEY: process.env.FIRE_BASE_API_KEY,
  FIRE_BASE_AUTH_DOMAIN: process.env.FIRE_BASE_AUTH_DOMAIN,
  FIRE_BASE_PROJECT_ID: process.env.FIRE_BASE_PROJECT_ID,
  FIRE_BASE_STORAGE_BUCKET: process.env.FIRE_BASE_STORAGE_BUCKET,
  FIRE_BASE_MESSAGING_SENDER_ID: process.env.FIRE_BASE_MESSAGING_SENDER_ID,
  FIRE_BASE_APP_ID: process.env.FIRE_BASE_APP_ID,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
};
